faketwit/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :tweets do
    resource :like
  end
# This is a nested resource. It will generate
# tweets/1/like instead of like/1.
# Let's take a look. In your terminal type rake routes. Notice the difference between relationships routes and the like routes.


  resources :relationships

  get 'profiles/:id' => 'profiles#show', as: :profile
  get 'profiles' => 'profiles#index'
  get "feed" => "profiles#feed"
  
  root 'tweets#index'

end

faketwit/app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :tweet
end

faketwit/app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user #This is the user that initiates the action
  belongs_to :friend, class_name: 'User' #This is the user being followed
end

faketwit/app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  has_many :likes
  
  validates :message, presence: true, length: { maximum: 140, too_long: "A tweet is only 140 characters max." }
end

faketwit/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Paperclip
  has_attached_file :avatar, styles: { medium: "300x300>", small: "175x175", thumb: "100x100>", tiny: "32x32" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_many :tweets
  has_many :relationships
  has_many :friends, through: :relationships
  has_many :inverse_relationships, :class_name => "Relationship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_relationships, :source => :user
  has_many :likes

  def likes?(tweet)
    tweet.likes.where(user_id: id).any?
  end
  # Remember Fat Model, skinny controller?
  # def likes?(tweet)
  # likes? is the name of our method, tweet is the argument.
  # tweet.likes.where(user_id: id).any?
  # We're looking for the user.id.
  # .any? returns true or false.


  validates :username, presence: true, uniqueness: true

end

faketwit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters

     devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation,
       :name, :username, :bio, :location, :avatar) }

     devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation,
       :current_password, :name, :username, :bio, :location, :avatar) }

   end
end

faketwit/app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet

  def create
    @tweet.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to request.referrer }
    end
  end
  # @tweet.likes.where(user_id: current_user.id).first_or_create
  # This is saying return the first user with these arguments. If it doesn't exist create it with the same arguments. Remember @tweet is being set with the before_action and def set_tweet.



  def destroy
    @tweet.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to request.referrer }
    end
  end

  private

    def set_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end
end

faketwit/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    #This sets @user to a user based on their id
    @user = User.find(params[:id])
  end

  def index
    #This sets @users to every User in our database
    @users = User.all
  end

  def feed
    @tweets = Tweet.where("user_id in (?) OR user_id = ?",
    current_user.friend_ids, current_user).order('created_at DESC')
  end
# @tweets = Tweet.where --> Tweet.where is a query.
#
# user_id in (?) --> user_id is the column name. in specifies multiple records will be returned. (?) is an argument and it will take the first one we pass through it. In this instance it's current_user.friend_ids.
#
# user_id = ?  --> This is looking for one user_id. This will include the tweets from the current user because we pass current_user to it.

end

faketwit/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  # POST /relationships
  # POST /relationships.json
  def create
    @relationship = current_user.relationships.build(friend_id: params[:friend_id])
    if @relationship.save
      flash[:notice] = 'Followed successfully.'
      redirect_to request.referrer
    else
      flash[:notice] = 'Unable to follow.'
      redirect_to request.referrer
    end
  end

  def destroy
    @relationship = current_user.relationships.find(params[:id])
    @relationship.destroy
    flash[:notice] = 'No longer following.'
    redirect_to request.referrer
  end

  private
    # Never trust parameters from the internet, only allow the white list through.
    def relationship_params
      params.require(:relationship).permit(:user_id, :friend_id)
    end
end

faketwit/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: "Tweet was successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  def new
    @tweet = Tweet.new
  end

  def show
  end

  def index
    @t =Tweet.all
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
    end
  end
  

  private

  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end

end

faketwit/app/helpers/application_helper.rb
module ApplicationHelper
end

faketwit/app/helpers/likes_helper.rb
module LikesHelper
end

faketwit/app/helpers/profiles_helper.rb
module ProfilesHelper
end

faketwit/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

faketwit/app/helpers/tweets_helper.rb
module TweetsHelper
end

faketwit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>Faketwit</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "assets/stylesheets/styles.css" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container">
      <%= yield %>
    </div>

  <!-- JavaScripts -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js" %>
  </body>
</html>

faketwit/app/views/profiles/feed.html.erb
<div class="row">
  <div class= "col-xs-3 card card-block">
      <div class="row">
        <%= image_tag(current_user.avatar.url(:small)) %>
        <h3><%= current_user.name %></h3>
        <h5><%= current_user.username %></h5>
      </div>
      <div class="row">
        <div class="col-xs-4">
          <span class="small text">TWEETS</span><br />
          <%= current_user.tweets.count %>
        </div>
        <div class="col-xs-4">
          <span class="small text">FOLLOWING</span><br />
          <%= current_user.relationships.count %>
          </div>
        <div class="col-xs-4">
          <span class="small text">FOLLOWERS</span><br />
          <%= current_user.inverse_relationships.count %>
          </div>
      </div>
      <h5><p><%= current_user.bio %></p></h5>
      <h5><%= current_user.location %></h5>
      <h5>Joined on <%= current_user.created_at.strftime("%B %Y") %></h5>
    </div>
    <div class= "col-xs-1"></div>

    <div class= "col-xs-7 card card-block">
<!-- Bootstrap 3 well -->
          <%= render 'tweets/form' %>
<!-- Bootstrap 3 well -->
        <% @tweets.each do |tweet|%>
        <%= image_tag(tweet.user.avatar.url(:thumb)) %>
        <strong><%= tweet.user.username %> </strong><small>tweeted <%= time_ago_in_words(tweet.created_at) %> ago</small>
        <br />
        <br />
        <%= tweet.message %>
        <br />
        <br />
        <% if current_user.likes?(tweet) %>
          <%= link_to tweet_like_path(tweet), method: :delete do %>
            <i class="fa fa-heart-o" aria-hidden="true"></i>
          <% end %>

          <% else %>
            <%= link_to tweet_like_path(tweet), method: :post do %>
            <i class="fa fa-heart" aria-hidden="true"></i>
          <% end %>
        <% end %>
        <br />
        <hr>
        <% end %>

  </div>
</div>

faketwit/app/views/profiles/index.html.erb
<h1>All Users</h1>
<% @users.each do |user| %>
  <%= link_to user.username, profile_path(user) %><br />
<% end %>

faketwit/app/views/profiles/show.html.erb
<div class="row">
  <div class= "col-xs-3 card card-block">
      <div class="row">
          <%= image_tag(@user.avatar.url(:small)) %>
              <h3><%= @user.name %></h3>
                  <h5><%= @user.username %></h5>
      </div>
       <div class="row">
         <div class="col-xs-4">
           <span class="small text">TWEETS</span><br />
                <%= @user.tweets.count %>
          </div>
           <div class="col-xs-4">
             <span class="small text">FOLLOWING</span><br />
              <%= @user.relationships.count %>
                  </div>
                  <div class="col-xs-4">
             <span class="small text">FOLLOWERS</span><br />
              <%= @user.inverse_relationships.count %>
                  </div>
         </div>

        <h5><p><%= @user.bio %></p></h5>
        <h5><%= @user.location %></h5>
        <h5>Joined on <%= @user.created_at.strftime("%B %Y") %></h5>

        <br />
        <br />
        <% if current_user.id != @user.id %>
          <% if current_user.friends.include?(@user) %>
           <%= link_to "Following", relationship_path(current_user.relationships.find_by_friend_id(@user)), :method => :delete, class: "btn btn-primary", id:"unfollow_btn" %>
          <% else %>
            <%= link_to "Follow", relationships_path(:friend_id => @user), method: :post, class:"btn btn-success" %>
          <% end %>
        <% end %>
    </div>
    <div class= "col-xs-1"></div>

  <div class= "col-xs-7 card card-block">
      <% @user.tweets.each do |tweet| %>
          <%= image_tag(tweet.user.avatar.url(:thumb)) %>
        <strong><%= tweet.user.username %> </strong><small>tweeted <%= time_ago_in_words(tweet.created_at) %> ago</small>
        <br />
        <br />
        <%= tweet.message %>
        <div class="panel-body">

        <% if current_user.likes?(tweet) %>
          <%= link_to tweet_like_path(tweet), method: :delete do %>
            <i class="fa fa-heart-o" aria-hidden="true"></i>
          <%end%>
         <% else %>
          <%= link_to tweet_like_path(tweet), method: :post do %>
            <i class="fa fa-heart" aria-hidden="true"></i>
          <%end%>
        <% end %>
        <br />
        <hr>
        </div>
      <% end %>
    </div>
  </div>

faketwit/app/views/shared/_likes.html.erb
<% if current_user.likes?(@tweet) %>
  <%= link_to 'Unlike', tweet_like_path(@tweet), method: :delete %>
<% else %>
  <%= link_to 'Like', tweet_like_path(@tweet), method: :post %>
<% end %>

<%= @tweet.likes.count %>

liked by:
<%= @tweet.likes.each do |like| %>
  <br />
    <%= like.user.username %>
    <br />
<% end %>

faketwit/app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand"></a>

  <ul class="nav navbar-nav">
    <li class="nav-item">
    <a class="nav-link"><%= link_to "All Tweets", root_path %></a>
    </li>

    <li class="nav-item">
      <a class="nav-link"><%= link_to "Edit Profile", edit_user_registration_path %></a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="#"><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></a>
    </li>
  </ul>
  
  <form class="form-inline pull-xs-right">
    <input class="form-control" type="text" placeholder="Search">
    <button class="btn btn-success-outline" type="submit">Search</button>
  </form>
</nav>

faketwit/app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
<% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message, placeholder: "Tweet"   %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

faketwit/app/views/tweets/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

faketwit/app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Whatever, this is just a header</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @t.each do |x| %>
      <tr>
        <td><%= x.message %></td>
        <td><%= x.user.username %></td>
        <td><%= link_to 'Show', x %></td>
        <td><%= link_to 'Edit', edit_tweet_path(x) %></td>
        <td><%= link_to 'Destroy', x, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

faketwit/app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

faketwit/app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user.username %>
</p>
<%= render 'shared/likes' %>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>